- name: Ensure Home Directory Exist
  file:
    path: "{{ go_user_home }}"
    state: "directory"
    mode: 0755


- name: Create GO Account Group
  group:
    name: "{{ go_group }}"
    state: present
  become: true


- name: Create GO Account User
  user:
    name: "{{ go_user }}"
    group: "{{ go_group }}"
    home: "{{ go_user_home }}"
    shell: "/bin/bash"
  become: true


- name: Ensure Home Directory is Owned by Go Agent
  file:
    path: "{{ go_user_home }}"
    owner: "{{ go_user }}"
    group: "{{ go_group }}"
    state: "directory"
  become: true


- name: "Ensure GO User .ssh dir exists and has correct owner/group"
  file:
    path: "{{ go_user_home }}/.ssh"
    state: directory
    owner: "{{ go_user }}"
    group: "{{ go_group }}"
    recurse: yes
    mode: 0750
  become: true


- name: "Add CD_SVC User Private Key"
  template:
    src: "id_rsa.j2"
    dest: "{{ go_user_home }}/.ssh/id_rsa"
    owner: "{{ go_user }}"
    group: "{{ go_group }}"
    mode: 0600
  become: true
